### ISSUE TITLE
Драконы

### ISSUE THREAD

**Issue by FaceLess1** [uonline/universe#135]
я считаю, что пусть я не буду достаточно "стильным", но в игре должны быть драконы. в принципе, в виде монстров, божеств, РБ -- вот о чем вопрос, потому выделяю в отдельную карточку.

**Comment by FaceLess1** [comment]
я читал о неких "механических" драконах, которые породили "адские машины" (или как-то так). они натурально механические? а то Макс говорил мне на мое предложение ввести механических ботов, что я ебанулся.

**Comment by FaNatizM** [comment]
Механические драконы вымерли, их Империи стали руинами, которые запечатали дети Аэайрэла. Ну, я предполагал, что у гномов будут сильно развитые технологии(а не магия как у остальных рас), как раз за счёт того, что они попадут в руины или мастерскую Мёртвого Бога и так заполучат новые знания. Я даже фантазировал на тему дредноутов для высокоуровневых гномских солдат. Но это ещё не продумано.
А адские машины в Аду.

**Comment by FaceLess1** [comment]
блин, ну так они натурально механические? я не нашел инфы об их сотворении (не сами же собрались, даже Золотая армия в "Хеллбое 2" не создалась самостоятельно). возможно, кузня, где они создались впервые, могла бы быть неплохой локацией для чего-то там.

**Comment by FaNatizM** [comment]
В Генезисе было пару отдалённых упоминаний:
> ...но никогда не было у Бога Творца недостатка в делах. Не разделял он надежду Таарвена, что драконы смогут ужиться с эльфами. Чужды змеи были миру Эрии, а кроме того бессмертными они были и обладали частицей силы богов. Покончить с ними раз и навсегда задумал Аэайрэл, создав себе в помощь *собственную армию*. С тех пор Аэайрэл не выходит более на свет. В трудах и странствиях по подземному миру проводил он время, создавая множество *новых мастерских*. Там он готовил *воинов*, что должны были сразится с драконами, когда те посмеют покуситься на земные недра.

> Как и предсказывал Бог Мудрости, не под силу было Пантеону одолеть драконов в подобном бою. В страхе змеи уползли обратно в твердь. Здесь уж ждал их Бог Творец со своей *рукотворной армией*. Ни один потомок Великих Драконов не ушёл живым из владений Аэайрэла.

Я не задумывал, что игроки попадут в мастерские Аэайрэла или в руины Империй механических драконов. Разве что спустя очень много времени. Гномы лишь один раз попали туда по счастливой случайности.
> Когда отважнейшие из героев нашли в себе смелость исследовать одну из чревоточин, они обнаружили один из главных изъянов магии искажения Безумного Бога. Если через чревоточины демоны покидали ад, то прошедшие через них же гномы оказались в месте, на Преисподнюю совсем не похожем. То была одна из сокрытых в земной тверди мастерских мёртвого бога. На заре мира бог-творец прятал множество своих творений в глубинах мира, но одобраться до них смертым было не дано. Лишь сила бога могла открыть дорогу к сокровищам Аэайрэла.

Несмотря на то, что за всю истори гномам удалось побыать лишь в нескольких хранилищах своего бога, секреты творений, которые они увидели там не раскрыты до сих. Древние загадки, которые удалось решить гномьим мудрецам, творцы подгорного народа смогли отразить во множестве своих изобретений. Многие технологии времён демонического вторжения, гномы не смогли постичь до сих пор. Принципы работы печатей хранящих подгорные государства от чёрной магии, так и остаются тайной. Но всё же открытие мастерских Аэайрэла, толкнуло гномов на путь развития технологий.

*Примечание: под чревоточинами здесь подразумеваются адские врата, через которые демоны выходят из Ада.*
Посещение гномами, мастерской очень сильно изменило их народ и культуру, позволило победить демонов, а потом драконов.
А драконы, если и не механические, то металлические точно. В любом случае они созданы искусственно. Сейчас я описываю их историю в Генезисе, так что они ещё в разработке.

**Comment by FaNatizM** [comment]
Перенесено в wiki: [Драконы и драконорождённые](https://github.com/uonline/universe/wiki/%D0%94%D1%80%D0%B0%D0%BA%D0%BE%D0%BD%D1%8B-%D0%B8-%D0%B4%D1%80%D0%B0%D0%BA%D0%BE%D0%BD%D0%BE%D1%80%D0%BE%D0%B6%D0%B4%D1%91%D0%BD%D0%BD%D1%8B%D0%B5).
