### ISSUE TITLE
Лаш, Старый и Новый

### ISSUE THREAD

**Issue by FaNatizM** [uonline/universe#138]
# Лаш, Старый и Новый

Теги:
- Старый Лаш
- Эпоха Героев
- Эпоха Греха
- Эгида Дракона
- Змеи Прародители
- Таарвен
- Забвение
- Вечное Лето
- Лесной Король
- Союз
- Лес
- Чужие Войны
- Пантеон
- Восстание
- Новый Лаш
- Эпоха Раздора (?)
- Первые Великие Войны
- Вторые Великие Войны
- Колонизация
- Островная Империя
- Огненные Лорды
- Изгои
### Старый Лаш

История Старого Лаша начинается в Эпоху Героев, когда в мире воцарилась власть Эгиды Дракона. Использовав эльфов как рабов, змеи пытались изменить Эрию себе в угоду, возродив свою прежнюю родину. Вечное Лето, ящеры и дракониды, элементали и атронахи - были лишь первыми этапом экспансии, созданием для драконов более-менее комфортных условий жизни в Эрии. Первым же настоящим шагом к возрождению мира Таарвена, стало создание огромного куска тверди из гор ..., свободно парящего в пространстве, и способного менять своё положение. Размеры Старого Лаша поражали воображение. В те древние времена это был край способный вместить небольшое государство. На нём были и горы, и долины и плато, и реки и озёра. Во времена, когда эльфы восстали против змеев, и рабы захватили собственное творение, на Лаше было возведено несколько крепостей, а сам он представлял из себя выжженные войной с драконами пустоши. Но к концу Эпохи Героев Старый Лаш начал процветать, преображаясь на глазах. Многие секреты драконов узнавали приближённые к ним рабы, и со временем в Лесу стали ходить самые разные слухи. По завершению войны про бунтарей с Лаша уже говорили, что они на самом деле истребили не всех драконидов, и некоторые из них укрыли в подземельях острова. Можно было услышать даже, что восстание не Лаше дело - коварного дракона, что задумал занять место Прародителей и извести своих старших собратьев.
Эпоху Греха Старый Лаш вошёл будучи государством насчитывающим несколько городов и целую сеть крепостей. Территория острова осваивалась для нужд сельского хозяйства и горного дела. Впрочем, в ходе войны Старый Лаш, так же приобрёл несколько колоний и на материке. Причём в самых разных частях света. Благодаря своей мобильности, Лаш мог без труда перемещаться от одной к другой, организуя довольно необычный способ товарооборота. Особенности были и во ведении боевых действий. Изначально Лаш оказался просто передвижным полем боя, куда дислоцировались, то одни, то другие войска, но со временем эльфам удалось получить полный контроль над островом. 
Большая часть побед в освободительной войне принадлежит именно Лашу. Он атаковал внезапно, используя тактику самих змеев - нанесение наибольшего урона в уязвимое место и быстрое отступление во избежание от ответного гнева драконов.
К концу Эпохи Героев, Лаш представлял из себя грозную военную силу. И всё же он избежал открытого столкновения с Лесом, в отличие от уничтоженного Союза. Это повлекло закономерную потерю всех крупных колоний и длительную изоляцию от мира. 
Назревание конфликта между Лесом и Лашем произошло по ряду причин. Несмотря на общие цели - свержение драконов, планы на будущее у союзников разнились. Многие обвиняли Лаш в пособничестве драконам, их увлечение культурой и изучение цивилизации змеев, наравне с постижением тайн их магии и впрямь выглядело подозрительным. Впрочем в этом не было ничего не обычного. Драконов побили их же оружием, а значит с самого начала Лаш подвергся риску потери лояльности Лесу, Союзу и даже всему эльфийскому народу. Слишком много знаний и силы таили в себе Прародители, чтобы так просто отвернуться от них. Вполне возможно, что в итоге Лаш постигло искушение.
Отношения с Лесом резко ухудшились сразу же после уничтожения последней из Империй змеев и смертью Лесного Короля. К экологическим, магическим и моральным вопросам добавились так же политические. Сопротивление рабов на Лаше поднял брат Лесного Короля, один из последних носителей божественной крови, который участвовал ещё в Восстании против Пантеона. В то время в Лесу сложилась ситуация, когда влияние обрели эльфы, не заинтересованные в том, чтобы трон занял сильный и харизматичный лидер. А брат Лесного Короля был куда большим, чем просто лидер. Ему шло десятое тысячелетие, и за это время он уже стал свидетелем Низвержения, сражался с тьмой Проклятого Бога и прошёл через тысячелетия рабства у драконов. Он уже был не просто лидером, но полубогом. Лаш имел все шансы, чтобы после завершения войны стать флагманом эльфийской расы, задающим развитие, и если бы не его сомнительная репутация, так бы и произошло. Свою лепту внёс и сам лидер Лаша. Он мог бы взять трон Леса силой, провозгласив Лаш второй столицей, но это был бы рискованный шаг. В Лесу назревало, то что в последствие получит имя проект "Забвение". Начиналась чистка истории.
Лаш избежал этого конфликта, чтобы вернуться через пять тысяч лет, когда Лес сам подставил себя под удар.
К тому времени Старый Лаш уже разительным образом изменился. Он стал островом-государством, плотно заселённым, половина которого была занята городами, а половина полями и садами, чтобы прокормить эти города. Лаш стал купелью магии, причём волшебство здесь развивалось по несколько другому пути. Оно входило во все сферы жизни граждан, заменяя любой физический труд. Элеметалы прислуживали в городах, работали на полях и шахтах, големы, под контролем атронахов, воевали на полях сражений. Но этого было недостаточно и скоро Лаш занялся магией изменения, создавая свою собственную расу-мутантов. Всё это закончилось Чужими Войнами, нанёсшими очередной удар по Эрии. И Лаш исчез, возможно снова на пять тысяч лет.
Сегодня Лаш это остров, представляющий из себя один большой город магов, и существующий лишь за счёт их волшебства. Огромные шпили башен устремляются частоколами в небо, окна в них сияют ярче звёзд по ночам. Твердь Лаша изрыта тоннелями и залами, где маги-техники забоятся о оборудовании вырабатывающем для города энергию, а маги-аграномы выращивают выведенных магическими мутациями животных и растения. Лаш изолирован от мира, и почти независим от него. О нём не любят говорить в Лесу, а за его пределами вспоминают лишь при пересказе сказок детям. А вот в подземном мире с выходцами из Лаша знакомы куда лучше. И гномы, и демоны, и нежить и даже стражи сокровищниц Таарвена не раз сталкивались с боевыми големами и магами невиданной мощи.
Никто в мире не знает, чего ожидать от этой грозной и таинственной силы Эрии, а мотивы и цели их бессменного лидера, возможно, не известны даже его подданным.
### Новый Лаш

История Нового Лаша начинается в Эпоху Раздора. Его создают могущественные волшебники Леса с целью показать всему миру, а в первую очередь Старому Лашу, на что они способны. Новый Лаш был поднят со дня моря, омывающего восточный берег Линара, между Первой и Второй Великими Войнами - людское название крупных конфликтов в которых приняли участие множество народов и государств.
Основной целью Лаша, помимо демонстрации силы Леса, стала слежка за Островной Империей людей, которая изрядно потрепала Лес за Первую Великую Войну, названную так же Колонизацией, и вообще контролем побережья и прилегающих вод. Во время Великих Войн, там содержался довольно сильный гарнизон и были переселены некоторые племена диких эльфов. Силы Нового Лаша участвовали во многих сражениях, но к концу Эпохи Раздора интерес Лесу к Новому Лашу пропал. Несмотря на всю спесь его правителей, остров оставался лишь провинцией на задворках государства, и рассматривался как нечто должное. Совет был готов мобилизовать Лаш в любой момент, но вкладывать в него средства, казалось опасным. В итоге в нынешнюю Эпоху Лаш оказался захвачен Огненными Лордами, давно мечтавшими о получении собственного уютного гнёзда. Теперь он превратился в оплот пиратов, контрабандистов и революционеров, которых покрывают главные оппозиционеры Леса - Изгои. Силы Нового Лаша, призванные когда-то защищать, ныне же терроризируют всё восточное побережье.

**Comment by FaNatizM** [comment]
[Немного английского на эту тему.](https://translate.google.com/?hl=ru#en/ru/lush)

**Comment by m1kc** [comment]
А чо, мне нравится.

**Comment by FaNatizM** [comment]
Мне тоже) А перед этим я ещё [вот это словечко](https://translate.google.com/?hl=ru#en/ru/Eerie) нашёл xD

**Comment by FaNatizM** [comment]
Про Старый Лаш перенесено [в wiki](https://github.com/uonline/universe/wiki/Лаш/).
