### ISSUE TITLE
География

### ISSUE THREAD

**Issue by FaNatizM** [uonline/universe#169]
# Эрия
- Внеземной план - мир вне Эрии
- Наземный план - мир созданный на поверхности Эрии Пантеоном
- Подземный план - мир созданный под поверхностью Эрии Аэайрэлом
## Внеземной план
- В Эпоху Сотворения - материал для сотворения Эрии
- В Эпоху Сотворения - Здесь звёзды, солнце и луна (о Эльберет, Гилтониэль!)
- До Низвержения - Место обитания Пантеона
- Всегда здесь - Царство вечной ночи, чьим хранителем/представителем/правителем (?) является Сэнивель, место где спрятан Аэайрэл
- После Низвержения - место куда попали Ушедшие с помощью Дара
### История развития

**Эпоха сотворения**
Изначально соврешенно гладкий шар, отражающий лишь свет звёзд и излучающий так же внутренний свет мастерской Аэайрэла. Бог Творец расчитывал, что жизнь будет проходить под твердью, но остальному Пантеону так понравился гладкий шар, что они решили, что жизнь будет на поверхности. Когда об этом узнал Аэайрэл он выковал мечи (будущие залежи металической руды в горах), которыми пронзал и резал мир изнутри. Так появились горы и вулканы. Таарвен создал "безопасные земли". Т.о. первые штрихи современного вида Эрии - великие горные массивы Эрии.

**Эпоха дракона**
- Лес
- Безлесье
- Неизвесные земли

В ходе битвы Аэайрэла со Змеями Прародителями, в последствие этой битвы значительная часть Изначального леса была уничтожена, так родился край Безлесья. Неизвестными землями были названы обширные восточные территории Леса мало исследованые перворождёнными.

**Эпоха богов**
- Лес
- Безлесье
- Неизвесные земли

В ходе войн и проявлений воли богов были измененны значительные территории Леса и Безлесья.

**Эпоха зверя**
- Предел
- Сокрытые земли

Низвержение Пантеона уничтожило часть тверди, поделив Наземный план на море и сушу. Безлесье и Лес основали континент - Предел. От Неизвестных земель уцелел другой континент - Сокрытые земли - родина людей. Между двумя континентами пролёг Единый - второй за историю Эрии океан. Остальные Неизвестные земли ушли под воду.

**Эпоха героев**
- Предел
- Сокрытые земли
- Лаш

В результате экспериментов Эгиды Дракона был создан Лаш - огромный остров способный летать.

**Эпоха гордыни**
- Линара
- Катор
- Дарсу
- Лаш
- Сокрытые земли (родина людей)

Победа над драконами далась дорогой ценой, юго-западные горы Предела, где затаился последний из Змеев Прародителей, были уничтожены в ходе грандиозного сражения гномов и драконидов в Подгорье. Предел раскалывается на три новых материка: Линар, Катор и Дарсу, а Безумный Бог получает возможность начать полномасштабное демоническое вторжение на родину людей. В результате Сокрытые земли постигает Катастрофа, и материк начинает медленно опускаться под воду.

**Эпоха раздора**
- Линара
- Катор
- Дарсу
- Лаш
- Новый Лаш
- Миритал
- Имперский Архипелаг

Спасаясь с затапливаемого континента, люди сначала заселяют острова между Линаром и Сокрытыми землями, а затем высаживаются на восточном побережье самой Линары. Начинаются Великие Войны в ходе которых эльфы создают огромный остров, парящий над морем к востоку от Линары, под названием Новый Лаш. Встплывает родина людей, эльфы называют её - Миритал.

**Современная эпоха**
- Линара
- Катор
- Дарсу
- Лаш
- Новый Лаш
- Имперский Архипелаг
- Миритал
### Лес

Обширные земли между 4-я огромными горными массивами на северо-западе, юго-западе, северо-востоке и юго-востоке. Два крупных озера, одно из которых в относительном центре Леса, с островом посередине, где так же были горы. Другое у юго-западных гор.
### Безлесье

Обширные земли между... На севере развитая система озёр и рек - Озёрный Край. На юге просторные равнины, редколесье и пустыни.
### Неизвестные земли

Земли не вошедшие в состав Леса и Безлесья.
### Предел

в отличие от Предела, сокрытые земли были дополнительно защищены Таарвеном, поэтому их не раскололо на части, а затопило...
### История развития

**Эпоха сотворения**
- Тоннели и залы Аэайрэла
- Столпы гор
- Трещины

Аэайрэл прокладывает тоннели и прорубает залы в глубиных Эрии, пока не узнаёт что жизнь будет на поверхности. В гневе он ранит твердь, создав как горы на поверхности, так и трещины в тверди. Столпы гор - мечи, которыми Аэайрэл пронзал землю. Их металл станет со временем рудными жилами. Так же через столпы гор можно добраться до центра Эрии.

**Эпоха дракона**
- Чревоточины и мастерские Аэайрэла
- Столпы гор
- Трещины

Залы становятся мастерскими для Бога Творца. Чревоточины - кратчайшие пути между мастерскими и поверхностью. В Трещинах укрываются младшие драконы.

**Эпоха богов**
- Чревоточины и мастерские Аэайрэла
- Столпы гор
- Сети пещер ночных эльфов
- Подгорье
- Империи механических драконов

Пещерные эльфы и искусственные армии Аэайрэла превращают Столпы Великаньих гор в Подгорье, развитую сеть тоннелей и пещер, идущих как в ширь так и в глубь и соединяющих Лес и Безлесье. Позднее механические драконы так же создают собственные подземные государства в Безьлесье, а пещерные эльфы углубляются ещё глубже в твердь, обнаружив чревоточины к главной мастерской Аэайрэла в центре мира. Так же из Трещин свою сеть неглубоких пещер создают ночные эльфы по всему Лесу и части Безлесья.

**Эпоха Зверя**
- Чревоточины и мастерские Аэайрэла
- Столпы гор
- Подгорье
- Уцелевшие сети пещер ночных эльфов
- Руины империй механических драконов
- Глубины

Из-за Низвержения большая часть сетей пещер ночных эльфов уничтожена. Разрушены глубинные тоннели Подгорья. Империи механических драконов превратились в запечатанные руины. Глубоко в тверди зарождаются новая, ещё никем не изведанная система подземелий - Глубины, в которые можно попасть лишь через Подгорье. Гномы пробираются в горы на северо-западе и юго-востоке, основывая ещё одно Подгорье там.

**Эпоха героев**
- Чревоточины и мастерские Аэайрэла  
- Столпы гор
- Подгорье  
- Руины империй механических драконов
- Уцелевшие сети пещер ночных эльфов
- Глубины
- Ад

Безумный Бог создаёт из центральной мастерской и темницы Проклятого Бога - Ад.

**Эпоха гордыни**
- Чревоточины и мастерские Аэайрэла
- Столпы гор
- Подгорье (теперь только в северных горах Катора и на Скалистом полуострове)
- Руины империй механических драконов
- Уцелевшие сети пещер ночных эльфов
- Глубины
- Ад
- Разломы

Подгорье Великаньих гор вместе с самими горами уничтожено, Подземный план Предела раскалывают Разломы - новые сети подземелий, особенно сильно развитые на западе Линара, юга Катора и северо-востоке Дарсу.

**Эпоха раздора**
- Чревоточины и мастерские Аэайрэла
- Подгорье
- Уцелевшие сети пещер ночных эльфов
- Столпы гор
- Руины империй механических драконов
- Глубины
- Ад
- Разломы

Подгорье Великаньих гор вместе с самими горами уничтожено, Подземный план Предела раскалывают Разломы - новые сети подземелий, особенно сильно развитые на западе Линара, юга Катора и северо-востоке Дарсу.

**Современная эпоха**
- Чревоточины и мастерские Аэайрэла
- Столпы гор
- Подгорье
- Руины империй механических драконов
- Уцелевшие сети пещер ночных эльфов
- Глубины
- Ад
- Разломы
- Поземелья Нового Лаша

Некоторые эльфы, что прошли через Великие Войны рассказывают, что под Новым Лашем существует система ходов и пустот, многие из которых ведут прямо в море...

**Comment by FaceLess1** [comment]
сейчас будет охренительно тупой вопрос, но ответ на него мне необходимо уяснить:
как соотносится т.н. "Подземный план" с "подземельями", упоминавшимися мной еще в #6?
"подземелья" -- это часть "Подземного плана", это синоним "Подземному плану", это совсем отвлеченное нечто? напомню, что там (в подземельях) задуманы рейды и одни из наиболее сложных битв, потому ответ на вопрос важен. 
вот в английской версии перевода особо путанницы нет между "subterranean"/"catacomb" и "Underworld" -- то или иное слово можно присвоить к одному понятию, соответственно, другое -- к другому. а тут, в русской версии, выходит каламбурчик. нужна трактовка, короче.

**Comment by m1kc** [comment]
Я так понял, это одно и то же. Пара цитат:

@ryzhikovas  |  @FaNatizM 
--------|-----------
на материке Эрия, на котором и происходит действо, когда-то случилось очень мощное землятрясение, из-за которого появилось огромное число глубоких трещин. (так, по крайней мере, все думают)|Аэайрэл прокладывает тоннели и прорубает залы в глубиных Эрии, пока не узнаёт что жизнь будет на поверхности. В гневе он ранит твердь, создав как горы на поверхности, так и трещины в тверди. Столпы гор - мечи, которыми Аэайрэл пронзал землю. Их металл станет со временем рудными жилами. Так же через столпы гор можно добраться до центра Эрии.
Первыми спуститься туда попробовали эльфы, которые обнаружили, что трещины, по крайней мере, некоторые, соединены между собой норами, причем большими|пещерные эльфы углубляются ещё глубже в твердь, обнаружив чревоточины к главной мастерской Аэайрэла в центре мира
Много позднее разломами заинтересовались орки|_Облом, в Генезисе нет орков. Точнее, упоминаются пару раз и на этом всё, у них нет истории._
Ближе к "нашим" дням стали поговаривать о каких-то огромных тенях в туннелях и неожиданных обвалах.|ночные эльфы ушли на помощь своему божеству, жадно вгрызаясь в подземные глубины, став тёмными эльфами, детьми подземелий, исчезнувшими как казалось тогда навсегда
Сейчас, во время появления персонажа в мире игры, среди нижних орков царит легкая паника, похоже, что-то в привычных уже разломах зарождается чужая им жизнь.|_Облом, в Генезисе нет орков. Точнее, упоминаются пару раз и на этом всё, у них нет истории._

То бишь орки улетели, а остальное всё осталось.

**Comment by FaNatizM** [comment]
@FaceLess1 то о чём ты написал, и то что ты имел ввиду в #6 (после ВоВ как минимум) в ММО назвается инстанс или данж. Простыми словами и буквально это расшифровывается как нечто вроде "постоянная зона повышенной опасности". Звучит криво, но если перечислить свойства этой штуки, то всё встанет на свои места. Итак, основные критерии инстанса.
* Имеются фиксированные входы и выходы. Т.е. попасть и покинуть инстанс вы можете, только так как это было срежиссировано разработчиком (если он не совсем индус конечно). Проще говоря, инстанс это не поляна, на которую можно зайти с севера, юга, востока, из леса, из-под пенька или упасть с неба. Упрощённо инстанс - это тоннель, вы заходите в него через вход, а чтобы он засчитывался пройденным должны выйти через выход.

* Обычно в инстанс пускают только игроков *объединённых в группу*. Считается, что инстанс своего уровня слишком сложен для прохождения игрока в одиночку. Там рядовые монстры в разы сильнее чем, монстры того же уровня вне инстанса, а боссы и вовсе намного сильнее игрока своего уровня. Ну и награда соответствующая.

* Инстанс существует отдельно от глобального мира, и генерируется непосредственно для входящей в него группы. Т.е. в один и тот же инстанс может в один и тот же момент времени зайти любое число групп игроков и каждая из них попадёт в свою копию инстанса.

* Сам по себе инстанс подразумевается как цельное *приключение*, т.е. сценарий задуманный разработчиком. Ловушки, головоломки, западни и всё такое прочее. Инстанс должен восприниматься как нечто цельное и продуманное.

Соответственно пещера с пауком за городом это не обязательно инстанс. Таких пещер может быть великое множество. В ВоВе на каждой локации обычно присутствует 2-4 таких вот пещеры. Инстанс же может быть поставлен в абсолютно любых декорациях, лишь бы соответствовал основным критериям. В Вове, как уже отмечали, декорации были самые разные. Канализация под городом, в которой расплодились крокодилы, тюрьма где подняли бунт заключённые, целый город захваченный нежитью. Были даже *инстансы-путешествия во времения* (аля терминатор). Группе игроков предлагалось вернуться в определённый исторический период в определённое место, и сделать так, чтобы будущее настоящее случилось. Это могла быть какая-нибудь битва, штурм крепости или ещё чего. Например http://eu.battle.net/wow/ru/zone/the-culling-of-stratholme/ - собственно инстанс Вов, повторяющий события одной из миссий Warcraft 3 (которая называлась так же).
Как же инстанс соотносится с Подземным планом и о сравнении uworld и genesis опишу позже.

**Comment by FaceLess1** [comment]
с ВоВ не знаком (каюсь, мой косяк), только слышал о них и читал. но я отлично знаком с Диабло2.   там строгого "выхода" нет. зашел/вышел -- собственно, так я там и качался до 27 уровня Амазонкой. поэтому вот уяснения ответа на мой вопрос и важно. я не совсем определился: нужен ли нам жесткий выход, когда недостаточно подготовленный игрок просто обречет на смерть своего персонажа, если просто войдет туда, ибо выхода нет, или же можно будет выйти, срывая рейд.

**Comment by FaNatizM** [comment]
Диабло 2 не ММОРПГ и никаких инстансов там нет. В Вов на сервере играют тысячи человек, единовременно присутствуя на на огромной глобальной карте (ну почти так). В Диабло 2 максимальная численность сервера - 8 человек. В Вов есть инстансы, которые называют *героические рейды* и они рассчитаны на прохождение группами по 15-25 человек, что в разы превышает численность сервера Диабло 2. При этом рейд проходится за несколько часов, а Д2 забег на финального босса за шмотом измеряется в минутах. В Д2 нет никаких зон и обширных локаций, вся карта там это, практически и есть труба ведущая, от актового города до актового босса. В масштабах ВоВ Д2 сама по себе всего лишь инстанс, и при этом нужно учитывать, что если ты играешь на сервере Д2 один, то подразумевается что и босса ты завалишь один (ибо в синглплеере так и происходит).
Суть в том что, не нужно жёстко ассоциировать "подземелье" и подземелье. "Подземелье", "данж", "инстанс" это всего лишь исторически сложившиеся названия. Нужно абстрагироваться. Не каждая пещера должна содержать босса и сундук с сокровищами, и напротив босс и сундук с сокровищами не обязаны быть исключительно под землёй.
Про жёсткий вход, это конечно не совсем так как я написал в первом критерии. Мне сложно объяснить это своёство обобщением. Поэтому покажу на примере ВоВ:
Игроки объединяются в партию и заходят в инстанс. Для них генерируется их копия инстанса. Игрок может покинуть инстанс так же как он в него зашёл, ничего страшного при этом не происходит, он просто не будет получать опыт и учавствовать в розыгрыше выпадающего с монстров шмота или содержимого сундуков. А вот если игрок вздумает покинуть группу, даже находясь при этом в инстансе, рядом с другими сопартийцами, его оттуда просто выкинет ко входу и если он зайдёт в инстанс один, то для него сгенерируется его копия инстанса, где все монстры и шмот будут свеженькими.
Такова ситуация на пиратских серверах ВоВ, как на оффе не знаю не играл. Но я играл год назад в Newerwinter Online и там не пускает в инстанс группу в которой меньше 5 человек (не то что одного человека). Наверное потому что выделять серверный ресурс на 1-го человека это очень жирно.

PS 27 уровень в Д2 это очень мало для того чтобы говорить "я отлично знаком Диабло 2".

**Comment by FaceLess1** [comment]
нет, я действительно отлично знаком с Диабло, а 27лвл -- это всего лишь уровень, с которого открывается Аура чумы у Амазонки. а так -- доходил до выше 70-го. 75-й или больше даже.

**Comment by FaNatizM** [comment]
> вопрос закрыт.

ок
> Я так понял, это одно и то же. Пара цитат:
...

Ну замахнулся ты очень сильно со сравнением. Я точно не знаю, что Андрей имел ввиду под "материком Эрия", возможно как раз безкрайнюю сушу, без морей и океанов. Он вроде нигде не даёт определения. Ну или я что-то упустил. Я опираться на UWorld начинаю, где-то с Эпохи гордыни. До неё не было ещё никаких Линары, Катора, Дарсу, а и эльфы знать не знали, что есть ещё и какой-то там Миритал с людьми, а никаких орков вообще не существовало.
Эрию у меня сотрясают мощные землятресения три раза. Первый раз Аэайрэл - в Эпоху сотворения. Это что уже было процитировано. Второй раз сильно пошатнули мир низвергнутые боги:
> Низвержение Пантеона уничтожило часть тверди, поделив Наземный план на море и сушу. Безлесье и Лес основали континент - Предел. От Неизвестных земель уцелел другой континент - Сокрытые земли - родина людей. Между двумя континентами пролёг Единый - второй за историю Эрии океан. Остальные Неизвестные земли ушли под воду.

> Из-за Низвержения большая часть сетей пещер ночных эльфов уничтожена. Разрушены глубинные тоннели Подгорья. Глубоко в тверди зарождаются новая, ещё никем не изведанная система подземелий - Глубины, в которые можно попасть лишь через Подгорье.

Третий раз пострались гномы и дракониды в конце Эпохи героев:
> Победа над драконами далась дорогой ценой, юго-западные горы Предела, где затаился последний из Змеев Прародителей, были уничтожены в ходе грандиозного сражения гномов и драконидов в Подгорье. Предел раскалывается на три новых материка: Линар, Катор и Дарсу, а Безумный Бог получает возможность начать полномасштабное демоническое вторжение на родину людей. В результате Сокрытые земли постигает Катастрофа, и материк начинает медленно опускаться под воду.

> Подгорье Великаньих гор вместе с самими горами уничтожено, Подземный план Предела раскалывают Разломы - новые сети подземелий, особенно сильно развитые на западе Линара, юга Катора и северо-востоке Дарсу.

Собственно, то что Андрей обозначил как Разломы в UWorld, я точно так же назвал и у себя.
> Подземный план Предела раскалывают Разломы - новые сети подземелий, особенно сильно развитые на западе Линара, юга Катора и северо-востоке Дарсу.

Разломы появляются в конце Эпохи героев, тогда же когда Предел раскалывается на Линар, Катор и Дарсу. Более того, Разломы и есть причина этого раскола.
Ну и дальше согласно плану:
> Первыми спуститься туда попробовали эльфы, которые обнаружили, что трещины, по крайней мере, некоторые, соединены между собой норами, причем большими

На Линаре так и получилось, на Дарсу и Каторе эльфов почти не осталось, как и других народов...
> Много позднее разломами заинтересовались орки
> Ближе к "нашим" дням стали поговаривать о каких-то огромных тенях в туннелях и неожиданных обвалах.
> Сейчас, во время появления персонажа в мире игры, среди нижних орков царит легкая паника, похоже, что-то в привычных уже разломах зарождается чужая им жизнь.

Ну да, в Генезисе про это ни слова(но об этом ниже), но скорее всего будет как написано в UWorld.

Теперь на тему Подземного плана. Андрей вводил Разломы, чтобы создать базу для генерации контента инстансов. Я ввёл Подземный план для возможного ввода в игру ещё трёх выделенных игровых народов, которые мне показались вполне подземными. Т.о. Подземный план задумывался как полноценный мир, такой же как и наземный. Там тоже политика, войны, вражда за ресурсы и территории. Только всё мрачнее, подземелья всё-таки. Кроме того, раз уж мы вводим дополнительные расы со временем, то и в Подземном плане, родине новых народов, монстры должны быть страшнее, войны кровавее и всё в этом духе.
Когда игра стартанёт с тремя оригинальными расами, взаимодействие с Подземным планом будет минимальное. Из локаций для посещения это Разломы, возможно части Подгорья, и некоторые из уцелевших пещер ночных эльфов. Соотвественно из подземных народов игроки встретят лишь каких-нибудь гоблинов, кобольдов, троллей, драконидов, слабых демонов и сектантов, а так же восставших мертвецов, под контролем каких-нибудь призраков. От гномов, нежити (некромантов) и демонов Ада, можно будет разве что наблюдать следы присутствия. Глубины, Подгорье, Ад, Руины мех драконов, мастерские Мёртвого Бога, чревоточины всё это должно было появляться только с вводом в игру трёх других игровых народов, ну или просто со временем, если новые народы вводить не будем.

Теперь на тему Генезиса. Дело в том что в Генезисе ничего про Подземный план нет, а то что есть устарело и не согласуется с историей Наземного плана. Сейчас у меня 24 страницы занимает генезис эльфов, генезис гномов - 6, генезис нежити - 9, генезис демонов - 6. Последние три в сумме меньше первого... А я не могу сказать, что написал про эльфов всё, там где-то половина. У них самая длинная история, часть которой будет досказана в генезисе орков, потому что эти расы сильно связаны. У них решающее место в ключевых моментах истории. Поэтому писать про них довольно муторное занятие. И всё же без них нельзя начинать рассматривать остальные расы и народы (кроме людей, которые жили в относительной изоляции от остального мира). Так что с Генезисом нужно быть осторожным, а пользоваться я предлагаю в основном Тезаурусом - справочником, куда я буду заносить вещи выработанные при доработки Генезиса. Определения я стрался давать краткие, везде ссылаясь на эпохи и народ, который ввёл это понятие. То что есть в Тезаурусе, точно имеет место, а вот с Генезисом такой принцип не сработает. Например, цитата из генезиса орков
> **Последствия Магических Войн**
Сопровождавшаяся бесчисленными смертями эпоха Магических Войн закончилась колоссальным возмущением в сотни раз усилившегося магического поля. пришла *Эпоха Охоты*

Что такое Эпоха Охоты? Я не знаю, я придумал это отчасти просто как название, но до конца так и не продумал. Сейчас уэе не думаю что она есть или будет в дальнейшем.

**Comment by m1kc** [comment]
> Очищение Стратхольма

Господи, они сделали мой день.

> называет [червоточины](https://ru.wikipedia.org/wiki/%CA%F0%EE%F2%EE%E2%E0%FF_%ED%EE%F0%E0) чревоточинами

:palm_tree:

> Я точно не знаю, что Андрей имел ввиду под "материком Эрия"

Когда-то планировался только один материк. По-современному это Линара. Так, стоп. Линара же. Почему у тебя везде "Линар"?

**Comment by FaNatizM** [comment]
> Когда-то планировался только один материк. По-современному это Линара. Так, стоп. Линара же. Почему у тебя везде "Линар"?
Не знаю, увидел Линар где-то, и подумал что так правильно.

**Comment by FaceLess1** [comment]
нам бы какую-нибудь локацию где-то в пещере снежных гор, где будет находиться топор (или меч) во льду -- по аналогии с мечом в камне. достать его невозможно -- это сделает позже некий НПС, который, скорее всего, станет позже РБ. 
кроме прочего можно еще некоторый сет доспехов погрузить в ледяное озеро -- тоже некий НПС их достанет.
это заметка чисто для истории.

**Comment by FaceLess1** [comment]
давайте сказки поработают на нас и запилим какую-нибудь сюжетную (или внесюжетную) кул-стори с "бобовым зернышком" и бобовым стеблем?

**Comment by FaNatizM** [comment]
Перенесено в wiki: [Геология Эрии](https://github.com/uonline/universe/wiki/%D0%93%D0%B5%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%8F-%D0%AD%D1%80%D0%B8%D0%B8).
