### ISSUE TITLE
Чатик

### ISSUE THREAD

**Issue by m1kc** [uonline/universe#186]

**Comment by m1kc** [comment]
@FaceLess1, слоты правильные? Слотов для свитков на поясе пока нет, это знаю.

![2015-07-03 17-26-48](https://cloud.githubusercontent.com/assets/1831620/8500854/b8d75154-21a8-11e5-8a94-d9cb470d8df2.png)

**Comment by FaceLess1** [comment]
а давай попробуем заменить "ноги" на "бедра"? "руки" еще катят. да, мне кажется, что слоты верны.

П.С. слоты на поясе не только для свитков, но и для зелий.

**Comment by m1kc** [comment]
> а давай попробуем заменить "ноги" на "бедра"?

Уверен? Вряд ли кто-то скажет, что штаны надеваются на бёдра - они закрывают всю ногу, а поверх них ещё крепятся наголенники.

**Comment by FaceLess1** [comment]
если брать совсем уж по исторической науке, то броня не надевается на голое тело или тельняшку. она надевается на специальные поддоспешники, которые являются тряпичными вещами, облегчающие (смягчающие) ношение металла. 
однако мы вольны в применении реальных правил ношения брони, ко всему прочему поддоспешники для каждой эпохи были со своими нюансами. по моей прикидке, они НЕ УЧИТЫВАЮТСЯ. я подумал, что ну их нахуй, поскольку так входит в коллизию экипировка. в таком случае перс появляется в штанах и рубахе на 1-м лвле. 
отдельного внимания заслуживают маги и прочее шаманье -- к ним не предусматривается тяжелая/средняя броня в том полном смысле, в котором она имеется у других классов. и с ними -- настоящая проблема(

**Comment by FaceLess1** [comment]
в таком случае давай так: внести "торс" и "ноги". для т.н. "melee warrior" там будет рубаха/поддоспешник в "торсе", а в "ноги" -- штаны/подоспешник. для магов и шаманов -- это все занимает какая-нибудь "мантия", "роба" и прочий шмот. ну а "ноги" -- заменить на "бедра". 

я не слишком запутанно изъяснился?

**Comment by m1kc** [comment]
Норм?

![2015-07-06 19-58-44](https://cloud.githubusercontent.com/assets/1831620/8528089/72c2d3aa-2419-11e5-8821-464b9d772ee4.png)

**Comment by FaNatizM** [comment]
Может на две колонки поделить? Вроде место есть.

**Comment by m1kc** [comment]
@FaNatizM Там ещё рюкзак справа.

**Comment by FaNatizM** [comment]
А его вниз?

**Comment by m1kc** [comment]
@FaNatizM Не надо его вниз.

**Comment by FaNatizM** [comment]
Ну может и не надо, я всё равно не вижу его на картинке. Что нормально то должно быть?

**Comment by m1kc** [comment]
@FaNatizM Да мы тут слоты согласовываем, не обращай внимания.

**Comment by FaNatizM** [comment]
[Успех]( http://stopgame.ru/newsdata/25391)

**Comment by m1kc** [comment]
@FaNatizM Мы, кстати, всё ещё ждём тебя в гейской конфе. Это как-то невежливо даже уже.

**Comment by FaNatizM** [comment]
А как туда попасть?

**Comment by m1kc** [comment]
Регайся в телеграме, дальше всё должно само произойти.

**Comment by FaNatizM** [comment]
Зарегался.

**Comment by m1kc** [comment]
Чёт дед Мороз в последнее время халтурит, совсем чудеса перестали происходить. Так, ладно. Контакт-лист подтянулся? Я там есть? Если да - пиши. Если нет - давай логин, по номеру не могу тебя найти. Или номер изменился?

**Comment by m1kc** [comment]
Rigor Veyron - это ты или случайное совпадение?

**Comment by FaNatizM** [comment]
Я, но там вроде как ник Fanat1zm должен быть.

**Comment by m1kc** [comment]
Осторожно, двери закрываются.
