### ISSUE TITLE
Новости с фронта — 2015

### ISSUE THREAD

**Issue by m1kc** [uonline/universe#194]
### :arrow_up: Предыдущий выпуск: #73

**Comment by FaNatizM** [comment]
## 06.11.2015

Ничего.

**Comment by FaNatizM** [comment]
## Новости от 13.11.2015

На этой неделе работаю над "печатной" версией Генезеса. Посетила интересная мысль, и возможно правильная. Некоторые части Генезиса вполне реально было бы написать в стихах, ибо и читать не так муторно было, и разбирать что написано, и писать тоже не надо будет большие тексты мне.

**Comment by m1kc** [comment]
## Новости от 13.11.2015

По нулям.

**Comment by m1kc** [comment]
## Новости от 20.11.2015

Большая часть действий в игре теперь совершается через POST-запросы. Причины того, что мы вообще стали тратить на это время, сводятся к трём вещам: защита от CSRF-атак, семантика, кэш.

**Comment by FaNatizM** [comment]
## Новости от 20.11.2015

Подготовил конкурсную версию генезиса к публикации. Посмотрим, что из этого выйдет.
Изменения:
* Орфография, пунктуация, порядок в предложениях;
* 3 главы удалены, т.к. информация в них устарела. Удалены тексты из главы эльфов, вследствие недоработки стиля повествования.
* Изменёна последовательность глав. Теперь она следующая: глава эльфов, глава драконов, глава людей, глава демонов;
* Добавлен текст про Новый Лаш;
* Переписана глава демонов;
* Термины тезауруса пронумерованы;

**Comment by FaceLess1** [comment]
**Новости от 21.11.2015**

выгружен круглый стальной щит.

**Comment by FaNatizM** [comment]
## Новости от 27.11.2015

Немного расписал государства людей.

**Comment by m1kc** [comment]
## Новости от 27.11.2015

Чё-то ковыряем. Исправили пару косяков в боте, перешли на новую систему сборки в uonline. Больше ничего.

**Comment by m1kc** [comment]
И, в общем, такая тема. Поскольку Санёк уже три недели не пишет новости, я так понимаю, он ставит под сомнение их ценность. Человек он не глупый, так что я, пожалуй, приму его мнение и отменю эту обязанность писать еженедельные отчёты. Новости отменяются, в общем. Сам тоже писать больше не буду.

**Comment by FaNatizM** [comment]
> Новости от 21.11.2015
выгружен круглый стальной щит.

идёт вразрез с

> Поскольку Санёк уже три недели не пишет новости, я так понимаю, он ставит под сомнение их ценность.

**Comment by m1kc** [comment]
Ну а я ко всему прочему ещё и слепой. Впрочем, неважно. Никто же не любит ебучую бюрократию, правда? Всё, бюрократии больше нет, возрадуйтесь.

**Comment by FaceLess1** [comment]
**Новости от 27.11.2015**

новостей нет.

**Comment by FaNatizM** [comment]
## Новости от 03.12.2015

Немного поправил разметку [дока по оркам](https://github.com/uonline/universe/blob/master/setting/now/races/orcs.md) и расширил описание громил. В планах изменение к структуре документа. И да, я пока не стал выкатывать на обсуждение эти тексты, и "втихую" пишу их в файлах, а не карточке по народам, как хотел. Вот такой вот я негодяй.

**Comment by FaNatizM** [comment]
## Новости от 10.12.2015
Не стал коммитить небольшие изменения в доке орков. Добавил территории и власти, но не расписал. А, ещё время от времени я рисую наброски представителей армий орков. Пока не очень успешно.

**Comment by FaceLess1** [comment]
**Новости от 13.12.2015**

выгружены гномий щит, дрова из непонятного дерева и старые кожаные башмаки.

**Comment by FaNatizM** [comment]
## Новости от 17.12.2015
Продолжаю работать над доком по оркам. Добавил народности. Опять же, подробно не расписывал. Выложил рисунок низкоуровнего орка игрока.

**Comment by FaNatizM** [comment]
## Новости от 24.12.2015
Ничего.

**Comment by FaNatizM** [comment]
## Новости от 30.12.2015
Завтра моё пребывание у компьютера будет сведено к решению узкого круга задач, посему отчитываюсь сейчас: ничего. На грустной ноте заканчивать год не хочется, поэтому пожелаю всем здоровья, добра, сил и средств в наступающем году. 

*PS В январе намучу эскизный отчёт за всю свою проделанную работу в проекте.*

**Comment by m1kc** [comment]
### :arrow_down: Продолжаем здесь: #195
