### ISSUE TITLE
Боевая система: внешний вид, механика работы с расстоянием и АоЕ спеллами

### ISSUE THREAD

**Issue by m1kc** [uonline/universe#213]
В ходе последних обсуждений выяснился такой момент, что никто не понимает, как вообще должен выглядеть бой. До сих пор непонятно, будет ли в бою такой фактор, как расстояние до цели, как будет выглядеть прицеливание АоЕ скиллами (и будут ли они вообще) и как со всем этим добром управляться. Несколько человек предлагали подобие миникарты, но никаких конкретных предложений и эскизов не было. К релизу эту тему нужно хотя бы в общем виде утрясти, потому что без понимания этих вещей мы не сможем придумывать, собственно, скиллы.

**Comment by Nowayinrf** [comment]
Побеседовали мы сегодня с Лёней, завтра он меня дополнит и, может, где-то подправит.
1) Перемещение по глобальной карте. Видится только 2 варианта: а) это есть точки, где стоят телепорты и обеспечивают мгновенное перемещение; б) это то, какие-то дилижансы, грифоны, да что угодно, но занимает порядочно так времени, и, соответственно, скорее всего делая переход скучным и унылым.
2) Перемещение по локальной карте, а именно, встречи с соперниками, встреча уже дерущихся ребят, и точки соприкосновения в одном месте человек так 30-ти. 
3) Боевая система. Даже когда нет лучников, с магами без дистанции никак не обойтись. Пока, единственный приходящий в голову вариант - боевая сетка (Герои, Дисциплс and so on), причем, в идеале, с переходами на другие события, для полномасштабных зарубов.

**Comment by FaNatizM** [comment]
Я подойду с другой стороны:

### Модель боя
Нужно определиться с тем в каком времени проходит бой. При этом я подразумеваю ситуацию, когда в PVP сражается сразу несколько игроков:

**Режим реального времени** - пока я не представляю как это будет выглядеть в текстовом формате. Как закликивание по кнопкам с откатом? В таком случае игрок вряд ли будет успевать читать все те сообщения из **лога боя** и одновременно принимать решения;

**Режим фаз** - цикл из двух фаз: **фаза обдумывания хода**, в которую все игроки обдумывают свои ходы, и **фаза действий**, в которую игроки эти ходы осуществляют. При этом у игрока перед глазами должна быть **шкала инициативы**, проще говоря - последовательность действий игроков в фазе боя. Т.е. игрок должен видеть в фазе обдумывания, что перед ним ходят ещё двое игроков, а после него трое, ну и обдумывать эту ситуацию. Допустим фаза обдумывания длится 3 минуты. У нас сражаются 6 игроков. На действие в фазе действий игроку даётся 15 секунд, за это время он должен успеть понять, что сделал предыдущий игрок, и возможно поменять своё решение, подготовленное за фазу обдумывания (с другой стороны фаза обдумывания как раз существует для того, чтобы игрок выработал несколько решений, зависящих от развития событий). Т.о. на фазу действий при 6 игроках уходит 1,5 минуты, и один виток цикла длится 4,5 минуты. При этом мы можем сделать кнопку "Я всё обдумал", и если все игроки её прожмут, то фаза обдумывания закончится раньше 3 минут. При этом так же, можно сделать **слот действия по умолчанию**, для ситуации, когда игрок за свои 15 секунд не принял решения. Это могут быть такие действия например: "атаковать ближайшего врага", "встать в защитную стойку", "медитировать".

**Пошаговый режим** - всё вроде тривиально, на ход вам даётся определённое время, допустим минута, как и другим игрокам. Вы можете завершить его раньше. На мой взгляд здесь есть пара минусов. Во-первых возможна ситуация из фолла, когда нужно ждать пока 30 крыс походят на свои пару клеток, чтобы зарезать одну из них, а потом ждать 29 крыс. Во-вторых возможна противоположенная. Допустим те же 6 игроков оказались "скорострелами" и завершили свои ходы за 5 секунд, и вот вам любителю подумать нужно успеть за одну свою минуту разобраться, что же они там "находили".

Отдельно хочу обозначить позицию насчёт **лога боя**. Т.к. текст это у нас будет основное средство визуализации, то лог боя должен:
 1. Быть адекватного размера (либо настраиваемого);
 * Иметь возможность быстрого удобного поиска;
 * Фильтры (допустим "фильтр РПГ" - описывает ходы игроков в "пафосных речах", сохраняя атмосферу, а "сухой фильтр" пишет всё максимально сжато);
 * Цветовую схему, возможно настраиваемую (хп зелёным цветом, мана синим, урон красным).

**Comment by FaNatizM** [comment]
> Максим Мусатов, [08.05.16 13:11]
> Реалтайм отпадает сразу, потому что у нас будут люди с медленным интернетом.
> 
> Максим Мусатов, [08.05.16 13:21]
> Я почему-то запомнил, что будут просто одновременные ходы. И вот это как раз сработать может, потому что что одна крыса, что восемь делают всё за один ход и при этом сам ход можно сделать довольно долгим.
> 
> Максим Мусатов, [08.05.16 13:44]
> Я не делю бои на PvP и PvE.
> 
> Максим Мусатов, [08.05.16 14:57]
> Да всё понятно. Но 15 секунд для медленного соединения - это мало.
> 
> Rigor Veyron, [08.05.16 15:41]
> сколько нужно для медленного соединения?
> 
> Максим Мусатов, [08.05.16 15:41]
> Тридцать.
> 
> Максим Мусатов, [08.05.16 15:47]
> Может быть, даже больше, вплоть до минуты. Тут надо ещё подумать, поскольку речь там идёт даже не о скорости передачи данных (трафик у нас почти нулевой), а об RTT и медленных пересылках потерянных пакетов.
> 
> Максим Мусатов, [08.05.16 15:48]
> И не очень понятно, насколько нестабильными бывают соединения и начиная с какой степени мы начинаем считать их неприемлемыми.
> 
> Максим Мусатов, [08.05.16 15:49]
> Но тридцать секунд - неплохая начальная оценка.

**Comment by FaNatizM** [comment]
Ещё вот что хотел обсудить:
Во-первых вопрос: Бой пошаговый. А собственно, что персонаж может сделать за ход? Другими словами будут ли в игре **очки действий** как ресурс, и от чего они будут зависеть?

### Поле боя
Старая добрая поговорка гласит "сильнее не тот кто сильнее, а тот у кого ружьё". Чем ближе пространство боя к 3-х мерному тем, бой интересней. Даже контактные бойцы не лупят друг друга дубинами до изнеможения, а передвигаются по полю боя. По этому стоит вопрос, как нам организовать взаимодействие игрока с этим полем боя:

**Ноудистанс** - вариант без дистанции. Но тогда не понятно, что делать с лучниками и магами, т.к. их главная особенность - убивать врага на расстоянии.

**Ряды** - в оригинальной серии дисциплес пошаговые бои происходили по принципу рядов. В первой шеренге стояли войны во второй, маги и стрелки. Были "широкие" существа, занимавшие и ячейки и первой и второй шеренги, но они были реально жирными. Чтобы достать до магов, воинам нужно было сначала полностью расчистить первую вражескую шеренгу. Можно не мудрствуя лукаво попробовать применить эту модель, с условием, что маги и лучники будут всюду таскать с собой миньнов-защитников разного толка.

**Шкала дистанции** - вводим характеристики персонажа **Поле зрения** и **Инициатива/реакция**. Этот вариант годится если мы не хотим связываться с двумерным пространством.

Т.е. ситуация: есть воин и маг. У война поле зрения = 7, у мага = 5. У война инициатива = 5, у мага = 3. Т.о. воин заметит мага раньше. После того как бой начался, мы даём войну право выбрать дистанцию между ним и магом в диапазоне от 5 до 7 (вдруг воин захочет из арбалета пальнуть) и первый ход. После этого хода, происходит расчёт инициативы и определяется основная последовательность ходов боя. Эту проверку воин так же выдерживает и снова ходит первым.

Другое дело если у вас поле зрения больше, но у противника выше инициатива. Вы определяете дистанцию между вами, и делаете первый ход. Далее, если у врага инициатива выше, происходит **перехват инициативы**.

Как следствие всё оружие и способности должны иметь характеристику **дистанция ведения боя**. При этом возможно, древковому оружию и длинным мечам давать дистанцию не 0, а 1.

Все существа так же должны иметь характеристику скорость передвижения.

Шкала дистанции рассчитывается в отношении каждого врага. И тут по сути, нужно ещё ввести такую характеристику как **размер** или **буффер пространства**. Т.е. 100 крыс могут относительно вас свести дистанцию к 0, а вот сотне лордов-демонов придётся потесниться.

Так же вводится понятие **место для манёвра**. Т.е. персонаж может пятиться по отношению в врагам. Место для манёвра определяется исходя из поля зрения персонажа. Т.е. маг не сможет пятиться дальше 5 ед. Дальше - бегство с поля боя.

**Координатная сетка** - случай для миникарты. В данном случае, я предполагаю, что расчёты позиций будут вестись аналогично представленным выше, но будут замуты с радиусами, т.е. расположение по границам обзора.

Ну к координатной сетке можно прикрутить миникарту с обязательной легендой, хотя бы на псевдографике для начала. А можно и с помощью разметки замутить.

PS пришла такая идея как **стаки мобов**. Если мы можем объединять мелкие вещи в инвентаре в стак, то почему нельзя десять крыс объединить в стаю?

**Comment by FaNatizM** [comment]
Лично я выступаю за **фазовый режим** боя и координатную сетку.

**Comment by FaNatizM** [comment]
> еще в "4" из воздуха появились "поле зрения" и "видимость". я пока не имею понятия как отнестись, т.к. есть свои плюсы и минусы. плюс: это реально прикольно, когда у тебя поле зрения узкое, и тут натыкаешься на банду гопников. с другой стороны навешивается туча всяких ништяков, где игрок может не разобраться. он может забросить не начав. да, его бабки останутся у нас, но порекомендует ли он нас своим друзьям? да ну вряд ли.

**Comment by m1kc** [comment]
## Предварительная концепция

Поле боя представляет собой хексы. Хексы никак не отрисовываются, кто где стоит - примерно разъясняется текстом.

> минимальная AoD — 3 гекса, а не 4. стандарт противника — 1 гекс, противники крупнее — 3 гекса, наиболее крупные — 7 гексов, гигантские (на всякий случай предусматриваю) — 13 гексов.

В будущем возможна визуализация в 2D/3D.

**Comment by m1kc** [comment]
Пошаговый режим, очки действия и прочее обсуждаем в отдельной карточке.
