### ISSUE TITLE
Экономика

### ISSUE THREAD

**Issue by FaceLess1** [uonline/universe#22]
я полагаю, экономика будет глобальнее, чем для одного персонажа?

**Comment by FaceLess1** [comment]
рискну переоткрыть тему и спросить: 
будет ли генератор стоимости предметов, который бы опирался на параметры стоимости сырья при создании, редкости вещи и ее объемов и рассчитывал таким образом конечную стоимость на рынке?
или вручную цены расставлять для каждого предмета придется?

**Comment by m1kc** [comment]
Я предполагал, что вручную. Вообще понятия не имею, как компьютер может рассчитать правильную цену: он понятия не имеет, это вот этот кинжал на +16 к атаке гораздо ценнее, чем вон тот амулет на +5 ловкости, хотя они оба делаются из железа и редко падают.
