### ISSUE TITLE
Игровые особенности

### ISSUE THREAD

**Issue by FaNatizM** [uonline/universe#224]
Список запланированных фич (идеи):

### 1. Создание персонажа
*В нашей игре игрок сможет выбирать, кем будет его игровой персонаж*.

* **Кастомизация** - нужно сделать так, чтобы игрок мог настроить персонажа под себя и обеспечить хотя бы видимость уникальности;
   * выбор биографии персонажа из вариантов (влияет на спавн нового персонажа в игре):
      * биогафия зависит от расы и народа;
   * определённо будет выбор портрета персонажа из вариантов (по 5 вариантов мужских и женских портретов на расу);
      * за донат мы можем рисовать заказные уникальные портреты;
* **Расы и народы** - предполагается наличие шести рас: люди, эльфы, орки, гномы, демоны, нежить. При создании персонажа, после выбора расы игроку необходимо выбрать принадлежность к народу: представителя **ведущего народа** или **представителя обобщённого образа расы**:
   * Расы разительно отличаются друг от друга во многих аспектах: физиология, образ жизни, культура, идеология, религия, ремёсла;
   * Ведущий народ лишь один из пула народов расы. Он определяет вектор развития расы на данный момент;
* При создании персонажа, часть его характеристик будет генерироваться из диапазона народа, а первые способности расы и народа присваиваться рандомно из древа способностей;

### 2. Развитие персонажа
*В нашей игре игрок сможет развивать персонажа так как ему захочется, занимаясь тем, что ему хочется: войной и политикой, ремеслом и торговлей, исследованием мира и приключениям. Игрок должен ощущать, что имеет все возможности создать уникального героя под свой стиль игры*.
* **Дерево/сеть специализаций** - все способности расы составляют образуют огромное дерево способностей:
      * Способности могут быть как активными (заклятья, приёмы), так и пассивными (ауры, стойки, пассивные умения);
      * Ветви дерева - "специализации", для открытия могут требовать от игрока превышения значений характеристик определённого порога, либо членства в определённой фракции (*обучение*), либо добычи определённого артефакта (*обучение/трансформация*):
         * Не все специализации требуют вступления во фракцию, существуют общие специализации расы;
         * Полноценное присвоение специализации происходит только при определённом числе очков в данной ветви (завершение обучения).
         * После присвоения специализации игрок получает определённый бонус.
         * Фракция может принять решение об изгнании игрока, если у того сильно упадёт репутация во фракции. После изгнания бонус специализации пропадает.
         * Игрок может изучить несколько специализаций;
         * Игрок так же может изучать способности из других специализаций, если удовлетворяет условиям изучения;
      * Область древа специализаций ведущего народа < древа представителя обобщённого образа расы;
     *  Область древа представителя обобщённого образа расы отражает особенности народов расы, отличных от ведущего народа;
      * Существуют "одиночные" способности расы и народа, открывающиеся с уровнем персонажа;
* **Профессии и крафт** - я бы тоже организовал единое дерево профессий для рас. Т.о. у нас будут два дерева "мирной" и "военной" деятельности;
* **Религия** - игрок может выбрать религию персонажа, дающую разные бонусы в зависимости от уровня **религиозности** и соблюдения догматов веры;
* Навык (**мастерство**) количественное выражение владения *чем либо* ;
* Отказ от потолка развития:
   * В игре не будет потолка развития. Будет система наследования, зависящая от расы. Бессмертные расы могут развиваться бесконечно. Смертные умереть, и продолжиться в *наследнике*;
* Смена расы. Будет возможность сменить "светлую расу", на "тёмную". Необратимо.

### 3. Предметы

* **Вещи**:
   * Вещи это предметы которые могут быть экипированы на персонажа;
   * Вещи различаются по редкости: общие (common), особые (uncommon), редкие (rare), уникальные (unique) и легендарные (legendary), мифические (mythical);
   * В игре будет широкий арсенал оружия, в том числе и оружия для магов;
   * Вещи так же делятся на расовые (крафтит представитель расы) и общие(крафтит кто угодно);
* **Одноразовые предметы**: пища, зелья (хотя возможно склянка будет расходоваться не за один заход), вещества-стимуляторы (типа грибов викингов), книги, дающие бонусы, отмычки, чертежи;
* **Многоразовые предметы**: те же зелья, ключи, снаряды;
* В игре будут **артефакты**;
* В игре будут квестовые предметы и вещи;
* **Крафтовые вещи**:
   * **Модульное оружие**;
   * **"Дикий крафт"** - сочетание разных подручных предметов для создания необычного оружия или брони (вандальное оружие орков например);
* Будут вещи влияющие на персонажа, например **проклятые предметы**, которые могут навесить эффект проклятья на использующего. Будут **одержимые вещи**, способные трансформировать персонажа в демона, нежить, одичалого;

### 4. Боевая система
*Боевая система должна быть интересной, вариативной, захватывающей и бросающей вызов. В бою имеют место и тактика, и стратегия. Бой не сводится к нажатию пары кнопок, в бою нужно думать и считать. Бой пошаговый. Китайский рандом не есть хорошо.*

* Характеристики существ:
   * Характеристики нулевого порядка: **размер**, **тип перемещения**, **видимость**;
   * Характеристики первого порядка: **здоровье**, **мана**, **выносливость** (очки действий), **энергия**, **поле зрения**, **инициатива**, **защита**, **точность**;
   * Характеристики второго порядка: **сила**, **ловкость**, **интеллект**;
   * Способности и атаки могут влиять любые характеристики существ;
* Бой проходит в **фазовом режиме**;
* Поле боя имеет вид **координатной сетки**, которая может иметь разную форму и размер;
* В бою можно использовать не только оружие и способности, но и прочие предметы;
* Бой будет **зависеть от окружения** (скинуть в обрыв, толкнуть на стену и т.п.);
* В игре будет **магия**:
   * Магия в игре выражается в способностях-заклинаниях;
   * Магия будет иметь возможность взаимодействовать с окружающей средой, зависеть от поля боя и менять поле боя;
* **Эффекты** навешиваются на существо/объект в ходе событий или применения способностей и влияют на его общее состояние:
   * Эффеты могут действовать только во время боя, а могут остаться на игроке и после выхода из боя и локации (кровотечение, отравление и т.п.);
   * Пребывание на локации может вызвать определённый эффект;

### 5. Взаимодействие с миром и ролеплей
*В нашей игре игрок будет ощущать себя частью мира. И в то же время чувствовать, что может изменить его*.

* **Фракционная система ИИ** - игрок может быть членом фракции или нескольких фракций:
   * **Фракция/сила/система** - любая общность существ, объединённая по каким-либо признакам: жители материка, раса, народ, государство, город, поселение, организация, культ, секта;
   * Фракции выстраивают иерархическую систему. Фракции могут включать друг друга;
   * Фракцию характеризует ряд ресурсов: экономических, территориальных, людских, военных, численность игроков и т.п.
   * **Репутация** - количественное выражение между существом и фракцией;
   * **Статус** - качественное выражение отношений между существом и фракцией;
   * Между фракциями так же существуют отношения;
   * Персонаж может принадлежать множеству фракций, в том числе на условии двойного агента;
* **Система "Рассказчик"**:
   * Все взаимодействия игрока с игрой должны быть стилизованы (возможно отключаемая фича);
   * Игрок это посетитель таверны. Игровой аккаунт это комната, которую снимает игрок. Персонажи это истории, которые слушает игрок у хозяина таверны. Игровые новости игрок так же получает через хозяина таверны (типа новостей обновления, глобальных событий, развитие глобального сюжета, войн крупных альянсов и т.д.). Т.о. общение с игрой в какой-то степени - диалог с ботом;

### 6. Взаимодействие с другими игроками
* **ПвП**:
   * Игроки могут образовывать **альянсы**, являющиеся фракциями;
   * Альянсы могут воевать друг с другом и другими фракциями;  
      * В игре будут ограбления караванов;
      * В игре будут стрелки;
   * В игре будут дуэли;
   * В игре будут арены;
* **ПвЕ**:
   * Игроки могут образовывать **группы**;
   * Игроки могут образовывать **рейды**;
   * Рейды от групп отличаются численностью и более сложной организацией;

### 7. Мир
*В нашей игре будет интересный и живой мир, богатый интересными персонажами, квестами, сюжетами и деталями. Должно будет создаваться ощущение, что мир развивается*.

* **Локации**:
   * Обычные - делятся по уровню детализации;
   * **Данж** - отдельно генерящаяся локация для игрока, группы, или рейда с квестами и задачами на ней, несколькими боссами и интересными заскриптованными игровыми ситуациями. Много сундуков с крутым лутом;
   * **Приключение** - отдельно генерящаяся локация для игрока или группы, с цепочкой задач, боссом и интересными заскриптованными игровыми ситуациями. В отличие от данжа приключение в большей мере вплетено в сюжет. Приключение проходится только один раз за конкретного персонажа (или группу). По мере развития сюжета приключения могут устаревать и отправляться в архив;
   * **Локации-пасхалки** - секретные локации выполненные в виде отсылки к какой либо игре, книге, фильме, сеттингу и т.д. Попасть туда можно либо абсолютно случайно, либо при выполнении определённых условий, логичных с точки зрения отсылки;
* **Глобальные и локальные события**:
   * Войны между государствами, народами, расами;
   * Глобальные катаклизмы, изменения карты мира;
   * Локальное событие это цепочка триггерных скриптов, активируемых на локации;
   * В игре будет генератор случайных событий;
* **Сюжеты, квесты**:
   * Будут глобальные сюжеты;
   * Игроки могут влиять на сюжеты и развитие игровой вселенной (см. Фракционную систему ИИ);
   * Цепочки квестов будут;
   * Минизадания;
* **Развитие поселений** - заселение новых территорий, технологии, стратегия, тактика, экономика, политика;
* **Проработка вселенной**:
   * Должно быть ощущение, что мир огромный и живой;
   * Должно быть ощущение, что мир "дикий", т.е. есть неизвестные, опасные земли. Есть место экспедициям, открытиям, приключениям;
      * Значительная часть мира не заселена игровыми расами, о ней мало информации;
   * Смена дня и ночи;
   * Смена времен года;
* **НПС**:
   * НПС не обладают перманентным бессмертием и бесконечным числом перерождений;
   * В рамках Событий НПС может быть убит навсегда; Его место может занять другой НПС;
   * Некоторые игроки могут получить функции НПС и выполнять их в офлайне;
   * НПС должны обладать регламентом жизни;
* **Монстры**:
   * Иерархия: Существуют обычные, минибоссы, боссы, чемпионы, рейд боссы;
   * Характеристики моба генерируются из диапазона;
   * Способности присваиваются из ряда способностей по вероятностям;
   * Мобы обладают регламентом поведения, что влияет на встречи с ними. Пр: волков больше вероятность встретить ночью;
   * Из мобов падает, только то что может в них быть;
* **Сундуки, тайники, сокровища, клады** будут;
* Будет структура **поселений/городов**, зависящая от расы:
   * Банки/ломбарды;
   * Шахты;
   * Кузницы;
   * Порты;
   * Постоялые дворы;
   * Фермы за стенами города;
   * Лесопилки;
   * Здания фракций/сил/систем;

### 8. Путешествия
*Игроку будут доступны разные средства передвижения, разной скорости и стоимости.*

* Ездовые животные;
* Платные ездовые животные - типа сменных лошадей;
* Караваны;
* Порталы - не считаю что мгновенное перемещение должно осуществляться за даром;
* Корабли;
* Дирижабли;

### 9. Компаньоны
*Игроки могут взять себе в помощь компаньонов. Компаньоны это не просто роботы, автоматически выполняющие любые приказы игрока. Они должны создавать ощущение живых существ с собственной волей.*

* **Компаньоны** - существа под управлением ИИ, сопровождающие игрока и помогающие в бою/путешествиях/профессии;
* Компаньоны имеют способности и могут знать профессии;
* Компаньоны могут присоединяться на разных условиях: оруженосцы, ученики (а возможно и учителя), подмастерья, наёмники и даже рабы;
* Компаньоны могут быть не игровой расы, например гоблины;
   * Следовательно компаньонов нужно будет экипировать соответственно их расе и народу;
* Компаньоны могут быть *квестовыми*:
   * В этом случае роли могут поменяться, и скорее игрок будет сопровождать компаньона, а последний сможет раздавать приказания;
* Максимальное число компаньонов - 2. Возможно на второго, нужно будет какое-либо разрешение (типа покупка места в таверне);
* **Питомцы** - животные компаньоны;

### 10. ИИ. Системы и агенты
*И существа и фракции/силы/системы это ИИ.*

* *Агент* это атомарный ИИ. Нижний уровень в иерархии принятия решений.
   * Любое существо не игрок в игре управляется агентом;
   * **Существо** это моб или НПС;
* **Фракция/система/сила** это ИИ, который может руководить агентами и другими фракциями;
* Свойства и возможности ИИ:
   * *Ресурсы*;
   * *Состояния*. Состояние ИИ влияет на принимаемые им решения;
   * *Решения*;
   * *Регламент поведения* определяется фракцией для своих агентов. При этом агенты имеют своё представление об этом регламенте;
   * **Цели**;

*список не полный, возможно внесение дополнений*

**Comment by FaceLess1** [comment]
дополняю к крафту: крафт предмета зависит от профессии. так, алхимик делает зелья, вытяжки, эссенции и прочее; кузнец специализируетсяна изделиях из металла — как правило, это элементы защиты и оружие, ювелир специализируется на аксессуарах и усилении иных предметов за счет инкрустации; галантерейщик и портной изготавливает как предметы одежды, так и некоторые иные вещи из ткани и кожи. 
рост уровня профессии зависит, в основном, от практики применения. под "практикой применения" подразумевается сразу два критерия: количество изготовленных вещей и качество изготовленных вещей. качество вещей напрямую влияет на характеристики предмета. так, для крафта оружия наивысшего класса недостаточно изготовлять мечи из одного только железа — для повышения навыка необходимо крафтить более качественные предметы. перед непосредственным крафтом будет информация о вероятном качестве предмете (среднее значение или диапазон), выраженная в процентах, где 1% — наиболее низкое из всех возможных, а 100% — наиболее высокое.

**Comment by FaceLess1** [comment]
дополняю к подземельям и рейдам:
рейд не всегда привязан к подземелью в. значении "под землей". это могут быть боссы и мини-боссы, чемпионы в локациях, недоступных для основной массы игроков (особо труднодоступная область леса, пещеры и прочее).

кроме того, дополнительное испытание в стиле survival на одного игрока либо же на команду игроков, суть которого заключается в максимальном истреблении противника. нормальная ситуация, когда на команду из 4 игроков нападает 20 слизней одновременно. в зависимости от успеха выдается/не выдается награда.

**Comment by FaceLess1** [comment]
дополняю по вещам и предметам: к предметам относятся не только предметы экипировки, но и предметы, которые могут быть использованы, израсходованы, применены каким-либо способом. это: квестовые предметы, еда, напитки, предметы экипировки, сырье, зелья, отмычки, книги, письма, чертежи, иные предметы...

**Comment by FaceLess1** [comment]
дополняю к монстрам: монстры кроме деления на обычных, боссов и т.д. имеют и собственные статусы, зависящие от их природы и требующие применения тактики боя. одним из основных делением является разделение на тех, кто имеет физическую оболочку и бестелесых. возможны и гибриды, сражение с которыми может перейти из одной формы в иную. 

кроме этого, также возможно наличие иных статусов монстра, которые могут быть как его собственными, так и приобретенными в ходе боя.

**Comment by FaceLess1** [comment]
почти никак не отображены **животные**. могут выполнять функции транспорта, тяговой силы и боевой единицы. в зависимости от животного -- могут иметь несколько функций сразу, но главная функция конкретного животного зависит от его экипировки и избранного назначения. 

животных можно экипировать. для тяговых -- это сумки (которые вместительнее обычных сумок персонажа), для боевых -- аммуниция, для того, чтобы животное было транспортным -- нужно седло и некоторая дополнительная экипировка. 

животных можно тренировать, повышая их характеристики. 

тренирует животное либо НПС в специальных лагерях (чем выше ранг животного -- тем выше квалификация требуется) или же сам персонаж, если знаком с такой профессией.

животных можно как покупать, так и приручать, для чего нужно изучить спец.навык. некоторых животных можно получить путем кражи яйца и последующего ухода, но требуются затраты и высок риск неудачи + необходим все тот же навык.

**Comment by FaceLess1** [comment]
дополняю к **порталам**: подразумевалось, что порталы будут находиться в далеких ебенях и будут способствовать преодолению действительно крупного расстояния между точками назначения, однако для продвижения к конкретной области потребуется еще какое-то время. 

в играх с одиночной кампанией порталы используются как чекпоинты или же как средство мгновенного перемещения, если иное не предусмотрено. 

мы же предусматриваем порталы как элемент сеттинга и способ передвигаться на крупные расстояния, портал не является чекпоинтом. 

для усложнения использования можно требовать наличие каких-то предметов за телепорт. с порталами можно делать задания по починке, захвату (перебив охраняющих портал противников).

**Comment by m1kc** [comment]
Архивировано сюда: :book: [Игровые особенности — сохранённая версия](https://github.com/uonline/universe/wiki/%D0%98%D0%B3%D1%80%D0%BE%D0%B2%D1%8B%D0%B5-%D0%BE%D1%81%D0%BE%D0%B1%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8-%E2%80%94-%D1%81%D0%BE%D1%85%D1%80%D0%B0%D0%BD%D1%91%D0%BD%D0%BD%D0%B0%D1%8F-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F)
