### ISSUE TITLE
Боевая система

### ISSUE THREAD

**Issue by m1kc** [uonline/universe#3]

**Comment by FaNatizM** [comment]
Пусть пока здесь будет:

> я предлагаю, например, запретить схватки более 32 единиц. может быть 1 персонаж и 31 соперник или 16х16 или иная вариация. я думаю, это оптимальное количество. 
> тут еще что Макс скажет важно: можем ли столкнуться с тем, что переполненное (более 32 или сколько там единиц) количество в одной схватке приведет к глюкам или нет.

**Comment by m1kc** [comment]
Карточку закрываю, так как здесь нет конкретного вопроса для обсуждения. Мы всё равно потом будем собирать эти карточки в общий список.
